<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Scripto.Desktop</AssemblyName>
    <RootNamespace>Scripto.Desktop</RootNamespace>
    <ApplicationIcon>Scripto.ico</ApplicationIcon>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <TargetPlatformVersion>7.0</TargetPlatformVersion>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
    <TargetPlatformDisplayName>Windows SDK 7.0</TargetPlatformDisplayName>
    <TargetPlatformSdkPath>C:\Program Files (x86)\Windows Kits\8.1\</TargetPlatformSdkPath>
    <UseOSWinMdReferences>false</UseOSWinMdReferences>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Scripto.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>lib\Microsoft.Web.WebView2.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.WinForms">
      <HintPath>lib\Microsoft.Web.WebView2.WinForms.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Include="lib\WebView2Loader.dll">
      <Link>WebView2Loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
